version: '3.8'

services:
  # Backend API Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: uwe-talk-backend
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - WHISPER_MODEL=small
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:5173,http://localhost:80
    volumes:
      - ./backend/models_cache:/app/models_cache
      - ./backend/feedback_data:/app/feedback_data
      - ./backend/.env:/app/.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

  # Frontend Service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: uwe-talk-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # Supabase Local (Optional - for development)
  supabase:
    image: supabase/postgres:15.1.0.117
    container_name: uwe-talk-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=uwe_talk
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - supabase_data:/var/lib/postgresql/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

volumes:
  supabase_data:
