# Generated by Django 5.1.4 on 2025-02-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VitalinkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('spo2', models.IntegerField(verbose_name='Oxygen Saturation')),
                ('temp', models.FloatField(verbose_name='Body Temperature')),
                ('bpm', models.IntegerField(verbose_name='Heartbeat Rate')),
                ('alert', models.CharField(max_length=300, verbose_name='AI Alert message')),
                ('sbp', models.IntegerField(verbose_name='Systolic Blood Pressure')),
                ('dbp', models.IntegerField(verbose_name='Diastolic Blood Pressure')),
            ],
        ),
    ]
