# Generated by Django 5.1.4 on 2025-02-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitalinkrecord',
            name='age',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vitalinkrecord',
            name='gender',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
